server:
  port: 8080


headers: "{'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123
.0.0.0 Safari/537.36','Referer': 'https://live.titan007.com/oldIndexall.aspx'}"

Playwright:
  Headless: true

Clientpool:
  MaxTotal: 100

Threadpool:
  codepoolsize: 100
  maximunpoolsize: 150

